-- generated by claude

local buffer = {}

-- ── helpers ──────────────────────────────────────────────────────────

local function checkBuf(b)
    assert(type(b) == "table" and b.__type == "Buffer", "expected buffer")
end

local function checkRange(b, offset, size)
    assert(offset >= 0 and offset + size <= #b.__data,
        "buffer access out of range")
end

-- IEEE-754 float utils (pure Lua, no ffi)
local function packf32(v)
    if v ~= v then return 0x7FC00000 end  -- NaN
    if v == 1 / 0 then return 0x7F800000 end -- +Inf
    if v == -1 / 0 then return 0xFF800000 end -- -Inf
    local sign = 0
    if v < 0 then
        sign = 1; v = -v
    end
    if v == 0 then return sign * 0x80000000 end
    local exp = math.floor(math.log(v) / math.log(2))
    local mant = v / 2 ^ exp - 1
    exp = exp + 127
    if exp <= 0 then -- denormal
        mant = (v / 2 ^ -126)
        exp = 0
    elseif exp >= 255 then
        return (sign * 0x80000000) + 0x7F800000
    end
    mant = math.floor(mant * 0x800000 + 0.5) % 0x800000
    return sign * 0x80000000 + exp * 0x800000 + mant
end

local function unpackf32(bits)
    local sign = bits >= 0x80000000 and -1 or 1
    local exp  = (bits % 0x80000000) / 0x800000
    exp        = math.floor(exp)
    local mant = bits % 0x800000
    if exp == 255 then
        return mant ~= 0 and 0 / 0 or sign * (1 / 0)
    elseif exp == 0 then -- denormal
        return sign * mant / 0x800000 * 2 ^ -126
    end
    return sign * (1 + mant / 0x800000) * 2 ^ (exp - 127)
end

-- ── construction ─────────────────────────────────────────────────────

local function ToLua(data)
    return "Buffer.Decode([[".. buffer.Encode(data) .."]])"
end

function buffer.create(size)
    assert(type(size) == "number" and size >= 0 and size == math.floor(size),
        "size must be a non-negative integer")
    local data = {}
    for i = 1, size do data[i] = 0 end
    return setmetatable({ __type = "Buffer", __data = data },
        {
            __tostring = function() return "buffer(" .. tostring(size) .. ")" end,
            __index = {ToLua = ToLua},
        })
end

function buffer.Encode(buffer)
    return Buffer.readstring(buffer, 0, Buffer.len(buffer))
end

function buffer.Decode(data)
    local new = Buffer.create(data:len())
    buffer.writestring(new, 0, data)
    return new
end

---Return the byte length of the buffer.
function buffer.len(b)
    checkBuf(b)
    return #b.__data
end

-- ── fill / copy ───────────────────────────────────────────────────────

---Fill `count` bytes starting at `offset` with `value` (0-255).
function buffer.fill(b, offset, value, count)
    checkBuf(b)
    count = count or (#b.__data - offset)
    checkRange(b, offset, count)
    value = value % 256
    for i = offset + 1, offset + count do
        b.__data[i] = value
    end
end

---Copy bytes from `src` into `dst`. Handles overlapping regions.
function buffer.copy(dst, dstOffset, src, srcOffset, count)
    checkBuf(dst); checkBuf(src)
    srcOffset = srcOffset or 0
    count     = count or (#src.__data - srcOffset)
    checkRange(src, srcOffset, count)
    checkRange(dst, dstOffset, count)
    if dstOffset > srcOffset then -- copy right-to-left for overlap safety
        for i = count - 1, 0, -1 do
            dst.__data[dstOffset + i + 1] = src.__data[srcOffset + i + 1]
        end
    else
        for i = 0, count - 1 do
            dst.__data[dstOffset + i + 1] = src.__data[srcOffset + i + 1]
        end
    end
end

-- ── unsigned integer read/write ───────────────────────────────────────

function buffer.readu8(b, offset)
    checkBuf(b); checkRange(b, offset, 1)
    return b.__data[offset + 1]
end

function buffer.writeu8(b, offset, value)
    checkBuf(b); checkRange(b, offset, 1)
    b.__data[offset + 1] = value % 256
end

function buffer.readu16(b, offset) -- little-endian
    checkBuf(b); checkRange(b, offset, 2)
    local d = b.__data
    return d[offset + 1] + d[offset + 2] * 0x100
end

function buffer.writeu16(b, offset, value)
    checkBuf(b); checkRange(b, offset, 2)
    value = value % 0x10000
    b.__data[offset + 1] = value % 256
    b.__data[offset + 2] = math.floor(value / 256) % 256
end

function buffer.readu32(b, offset)
    checkBuf(b); checkRange(b, offset, 4)
    local d = b.__data
    return d[offset + 1]
        + d[offset + 2] * 0x100
        + d[offset + 3] * 0x10000
        + d[offset + 4] * 0x1000000
end

function buffer.writeu32(b, offset, value)
    checkBuf(b); checkRange(b, offset, 4)
    value = value % 0x100000000
    b.__data[offset + 1] = value % 256
    b.__data[offset + 2] = math.floor(value / 0x100) % 256
    b.__data[offset + 3] = math.floor(value / 0x10000) % 256
    b.__data[offset + 4] = math.floor(value / 0x1000000) % 256
end

-- ── signed integer read/write ─────────────────────────────────────────

function buffer.readi8(b, offset)
    local v = buffer.readu8(b, offset)
    return v >= 0x80 and v - 0x100 or v
end

function buffer.writei8(b, offset, value)
    buffer.writeu8(b, offset, value % 256)
end

function buffer.readi16(b, offset)
    local v = buffer.readu16(b, offset)
    return v >= 0x8000 and v - 0x10000 or v
end

function buffer.writei16(b, offset, value)
    buffer.writeu16(b, offset, value % 0x10000)
end

function buffer.readi32(b, offset)
    local v = buffer.readu32(b, offset)
    return v >= 0x80000000 and v - 0x100000000 or v
end

function buffer.writei32(b, offset, value)
    buffer.writeu32(b, offset, value % 0x100000000)
end

-- ── float read/write ──────────────────────────────────────────────────

function buffer.readf32(b, offset)
    local bits = buffer.readu32(b, offset)
    return unpackf32(bits)
end

function buffer.writef32(b, offset, value)
    buffer.writeu32(b, offset, packf32(value))
end

-- f64 — uses two u32 halves (lo/hi), pure-Lua IEEE-754 decomposition
function buffer.readf64(b, offset)
    checkBuf(b); checkRange(b, offset, 8)
    local d    = b.__data
    local lo   = d[offset + 1] + d[offset + 2] * 0x100
        + d[offset + 3] * 0x10000 + d[offset + 4] * 0x1000000
    local hi   = d[offset + 5] + d[offset + 6] * 0x100
        + d[offset + 7] * 0x10000 + d[offset + 8] * 0x1000000
    local sign = hi >= 0x80000000 and -1 or 1
    local exp  = math.floor((hi % 0x80000000) / 0x100000)
    local mant = (hi % 0x100000) * 0x100000000 + lo
    if exp == 0x7FF then
        return mant ~= 0 and 0 / 0 or sign * (1 / 0)
    elseif exp == 0 then
        return sign * mant / 2 ^ 52 * 2 ^ -1022
    end
    return sign * (1 + mant / 2 ^ 52) * 2 ^ (exp - 1023)
end

function buffer.writef64(b, offset, value)
    checkBuf(b); checkRange(b, offset, 8)
    local sign, hi, lo = 0, 0, 0
    if value ~= value then -- NaN
        hi, lo = 0x7FF80000, 0
    elseif value == 1 / 0 then
        hi = 0x7FF00000
    elseif value == -1 / 0 then
        hi = 0xFFF00000
    else
        if value < 0 then
            sign = 0x80000000; value = -value
        end
        if value > 0 then
            local exp = math.floor(math.log(value) / math.log(2))
            if exp > 1023 then
                hi = sign + 0x7FF00000
            else
                local mant = value / 2 ^ exp - 1
                exp = exp + 1023
                if exp <= 0 then
                    mant = value / 2 ^ -1022; exp = 0
                end
                local mhi = math.floor(mant * 0x100000)
                lo        = math.floor((mant * 0x100000 - mhi) * 0x100000000 + 0.5)
                hi        = sign + exp * 0x100000 + mhi
            end
        end
    end
    local d = b.__data
    d[offset + 1] = lo % 256
    d[offset + 2] = math.floor(lo / 0x100) % 256
    d[offset + 3] = math.floor(lo / 0x10000) % 256
    d[offset + 4] = math.floor(lo / 0x1000000) % 256
    d[offset + 5] = hi % 256
    d[offset + 6] = math.floor(hi / 0x100) % 256
    d[offset + 7] = math.floor(hi / 0x10000) % 256
    d[offset + 8] = math.floor(hi / 0x1000000) % 256
end

-- ── string read/write ─────────────────────────────────────────────────

---Read `count` bytes at `offset` as a Lua string.
function buffer.readstring(b, offset, count)
    checkBuf(b); checkRange(b, offset, count)
    local t = {}
    for i = offset + 1, offset + count do
        t[#t + 1] = string.char(b.__data[i])
    end
    return table.concat(t)
end

---Write string `s` into the buffer starting at `offset`.
function buffer.writestring(b, offset, s, count)
    checkBuf(b)
    count = count or #s
    checkRange(b, offset, count)
    for i = 1, count do
        b.__data[offset + i] = string.byte(s, i)
    end
end
local function checkBits(offset, count)
  assert(type(offset) == "number" and offset == math.floor(offset) and offset >= 0,
    "bit offset must be a non-negative integer")
  assert(type(count) == "number" and count == math.floor(count)
    and count >= 1 and count <= 32,
    "bit count must be an integer between 1 and 32")
  assert(offset + count <= 32,
    "bit field (offset + count) must not exceed 32")
end

-- Build a bitmask of `n` ones (n <= 32), pure-Lua safe
local function mask(n)
  if n == 32 then return 0xFFFFFFFF end
  return 2^n - 1
end

-- ── buffer.readbits / writebits ───────────────────────────────────────

---Read an unsigned integer from `count` bits starting at bit `bitOffset`
---within the u32 at byte `byteOffset`. Bits are numbered 0 (LSB) to 31.
---
--- buffer.readbits(b, byteOffset, bitOffset, count) -> number
function buffer.readbits(b, byteOffset, bitOffset, count)
  checkBuf(b)
  checkBits(bitOffset, count)
  local word = buffer.readu32(b, byteOffset)      -- read 4-byte window
  local shifted = math.floor(word / 2^bitOffset)  -- shift right
  return shifted % (mask(count) + 1)              -- mask to `count` bits
end

---Write an unsigned integer `value` into `count` bits starting at bit
---`bitOffset` within the u32 at byte `byteOffset`. Other bits untouched.
---
--- buffer.writebits(b, byteOffset, bitOffset, count, value)
function buffer.writebits(b, byteOffset, bitOffset, count, value)
  checkBuf(b)
  checkBits(bitOffset, count)
  local m    = mask(count)
  value = math.floor(value) % (m + 1)             -- clamp to field width
  local word = buffer.readu32(b, byteOffset)      -- read existing u32
  local slot = m * 2^bitOffset                     -- positioned mask
  -- clear the target field then OR in the new value
  word = (word % 0x100000000)                      -- keep within u32
  local cleared = word - (word % (slot * (mask(count)+1)))
                      % (slot * (mask(count)+1))
  -- cleaner approach: zero the bits with modular arithmetic
  local low  = word % 2^bitOffset                  -- bits below field
  local high = math.floor(word / 2^(bitOffset+count)) * 2^(bitOffset+count)
  word = high + (value * 2^bitOffset) + low
  buffer.writeu32(b, byteOffset, word)
end

-- ── convenience: single-bit read/write ───────────────────────────────

---Read a single bit as 0 or 1.
--- buffer.readbit(b, byteOffset, bitOffset) -> 0 | 1
function buffer.readbit(b, byteOffset, bitOffset)
  return buffer.readbits(b, byteOffset, bitOffset, 1)
end

---Write a single bit (value must be 0 or 1).
--- buffer.writebit(b, byteOffset, bitOffset, value)
function buffer.writebit(b, byteOffset, bitOffset, value)
  buffer.writebits(b, byteOffset, bitOffset, 1, value)
end

return buffer
